name: 08 - Using Variables

on:
    push:
    workflow_dispatch:
env: 
    WORKFLOW_VAR: ' I am a workflow var'
    OVERWRITTEN: 'I will be overwritten'

jobs:
    echo: 
        runs-on: ubuntu-latest
        env:
            JOB_VAR: 'I am a job env var'
            OVERWRITTEN: 'I have be overwritten at job lvl'
       steps:
        - name: Print Env Variables
          env:
            STEP_VAR: 'I am step env var'
            step-var2: "I am another step env var"

          run: |
            echo "Step env var: ${{ env.STEP_VAR}}"
            echo "Step env var 2: $step-var2"
            echo "job env var: ${{ env.JOB_VAR}}"
            echo "workflow env var: ${{ env.WORKFLOW_VAR}}"
            echo "Overwritten: ${{ env.OVERWRITTEN}}"
        - name: Overwrite job variable
          env:
                OVERWRITTEN: 'I have overwritten at the step lvl'
          run: |
             echo "Step env var: ${{env.OVERWRITTEN}}"
