name: 16 - Working with Environments

on:
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging
jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{inputs.target-env}}
        env: 
            my-env-value: ${{vars.My_ENV_Value || 'default value'}}
        steps:
            - name: Echo vars
              run: |
               echo "Evn variable: ${{env.my-env-value}}"